# Generated by Django 3.2 on 2021-04-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_alter_image_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 16, 4, 42, 438493)),
        ),
    ]
